theme: jekyll-theme-minimal
title: Chi Bong's Demo Home Page
description: Welcome to my demo home page. This pages shows how easy it is to create a home page to showcase your projects.
logo: chibong2.png
